Map for mobile
geo-quiz/geo-quiz pull request #50
Opened 2022-10-31 08:27 UTC by Yuriks1

Divided map into three parts and created three separate components for each pair of continents.

2022-10-31 10:01 UTC, DarkendHall requested changes

2022-10-31 10:17 UTC, ToniKaru commented on frontend/src/components/ContinentMapMobileLeft.vue
> +    <h1>N.America / S. America</h1>
```suggestion
    <h1>The Americas</h1>
```

2022-10-31 10:35 UTC, Yuriks1 commented on frontend/package.json
> +        "@mdi/js": "^7.0.96",
No, these can be removed.

2022-10-31 12:41 UTC, Yuriks1 commented on frontend/src/views/HomeView.vue
> +                <GeoButton color="green" size="large" @click="router.push(isMobileOnly?'/quizMob':'/quiz')"> Play now</GeoButton>
Worked for me and Toni, needs to refresh for it to function.

2022-10-31 13:15 UTC, Yuriks1 commented on frontend/src/components/ContinentMapMobile.vue
> +</style>
Fixed indents.

2022-10-31 13:15 UTC, Yuriks1 commented on frontend/src/components/ContinentMapMobileRight.vue
> +</style>
Fixed indents.

2022-10-31 13:16 UTC, Yuriks1 commented on frontend/src/components/ContinentMapMobileLeft.vue
> +</style>
Fixed indents.

2022-11-01 14:39 UTC, DarkendHall approved these changes

2022-11-02 08:29 UTC, ToniKaru approved these changes
Everything works like butter!

2022-11-02 08:30 UTC, merged