Updated with continent
geo-quiz/geo-quiz pull request #9
Opened 2022-10-10 11:39 UTC by GreenGard

2022-10-10 15:11 UTC, DarkendHall requested changes

2022-10-10 15:11 UTC, DarkendHall commented on backend/routes/quiz.ts
> +});
```suggestion
});

```

2022-10-11 09:06 UTC, DarkendHall approved these changes

2022-10-11 09:10 UTC, OscarStjernfeldt approved these changes

2022-10-11 09:11 UTC, merged